M48
; DRILL file {KiCad 8.0.9-8.0.9-0~ubuntu22.04.1} date 2025-03-09T15:02:49+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-09T15:02:49+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.9-8.0.9-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0945
%
G90
G05
T1
X4.76Y-2.7973
X4.76Y-3.38
M30
